#ifndef AUTOSMS_H
#define AUTOSMS_H

#include <QObject>

class QTimer;
class GSModule;

class autoSMS : public QObject
{
    Q_OBJECT
public:
    explicit autoSMS(QObject *parent = 0);
    
signals:
    
public Q_SLOTS:
    void sendAutoGeneratedSMS();
private:
    QTimer * m_timer;
    GSModule *m_gsm;

    int m_sentSMS;

};

#endif // AUTOSMS_H
