#include "autoSMS.h"
#include <QSerialPort>
#include <QSerialPortInfo>
#include <QDebug>
#include <QDateTime>
#include <QTimer>

#include "GSModule.h"

autoSMS::autoSMS(QObject *parent) :
    QObject(parent)
{
    m_gsm = new gsmModule(0, true);
    connect(m_gsm, SIGNAL(readyToTransmit()), m_timer, SLOT(start()));

    m_timer = new QTimer();
    m_timer->setInterval(1000);
    m_timer->setSingleShot(true);
    connect(m_timer, SIGNAL(timeout()), this, SLOT(sendAutoGeneratedSMS()));


    qDebug() << "===== GSM Module =====";

    // Creates the serial port here because it changes a lots depending on the system it's run from.
    QSerialPort *serialPort = new QSerialPort();

    serialPort->setPort(QSerialPortInfo("ttyAMA0"));
    serialPort->setBaudRate(QSerialPort::Baud19200);
    serialPort->setDataBits(QSerialPort::Data8);
    serialPort->setParity(QSerialPort::OddParity);
    serialPort->setStopBits(QSerialPort::OneStop);
    m_gsm->initializeSerialConnection(serialPort);

}

void autoSMS::sendAutoGeneratedSMS()
{
    qDebug() << "Sending a sms";
    QString smsMessage = QDateTime::currentDateTime().toString() + " It look like it works!";
    m_gsm->sendSMS(smsMessage, "+46708783740");
}
